### ISSUE TITLE
Just a blank screen

### ISSUE THREAD

**Issue by tripleo1** [rochus-keller/OberonSystem#2]
I was able to install with the following steps:

* Patch

```diff
diff --git a/CPP/ObSystem.cpp b/CPP/ObSystem.cpp
index ca5cb93..6dba6d5 100644
--- a/CPP/ObSystem.cpp
+++ b/CPP/ObSystem.cpp
@@ -682,7 +682,7 @@ void System::ShowModules()
                {
                        Texts::_inst()->WriteString(_this->W, M->name);
                        Texts::_inst()->Write(_this->W, 0x9);
-                       Texts::_inst()->WriteHex(_this->W, int( M ));
+                       Texts::_inst()->WriteHex(_this->W, int( (long) M ));
                        Texts::_inst()->WriteHex(_this->W, M->code);
                        Texts::_inst()->WriteInt(_this->W, M->refcnt, 4);
                }else
```

* Make

```bash
ln -s ../OberonSystem CPP
qmake
make
```

* Run

```bash
cd ../
CPP/OberonSystem
```

All I'm getting is this

![oberon 2021-06-23 03-59-58](https://user-images.githubusercontent.com/50311859/123061173-62918500-d3d9-11eb-83ed-9e87624d7a59.png)

... and high CPU usage

I'm on Linux Mint 20.1 (Ubuntu 20.04) with qt 5.12

**Comment by rochus-keller** [comment]
Thanks for your interest. As I wrote in the readme the CPP version of the Oberon System is published for documentation purposes only; it used to work when I did my experiments on my i386 Linux machine some years ago, but I don't know whether it still works or is compatible with x86_64. These days I focus on my new compiler and IDE supporting a more modern version of Oberon (see screenshot below); it is also able to run the Oberon code i.e. Oberon System version in this repository, in case you want to have a look at it; but keep in mind it's work in progress and I do all this stuff in my spare time (which is limited).

Screenshot:
![grafik](https://user-images.githubusercontent.com/2523113/123081749-92af4700-d41e-11eb-85a4-9be417c3d5ae.png)

**Comment by tripleo1** [comment]
Yeah I had a feeling it was for 32 bit only.  Is there a way to regenerate the c++ files or a I completely on my own?

**Comment by tripleo1** [comment]
Alright. I have compiled ObnViewer.pro as per instructions. How do I run OberonSystem?

**Comment by rochus-keller** [comment]
ObnViewer.pro is used to build the OberonViewer; its primary feature is to view and navigate Oberon source code; it doesn't run Oberon code. If you want to run Oberon code, you can use the following projects:

OBNLC.pro creates a command line tool which translates Oberon-07 to Lua source code or LuaJIT bytecode and can also directly run the code because of the integrated LuaJIT; but it doesn't support the Oberon System backend.

OberonIde.pro creates the first version of the OberonIDE which supports Oberon-07 and is also suited to run the Oberon System; there is also a pre-built Windows 32 Bit and macOS 64 bit version ready for download.

ObxIde.pro creates the current version of the Oberon+ IDE (work in progress) which supports different Oberon language versions including my Oberon+ version; it is also suited to run the Oberon System; no pre-built versions yet.

I develop and run everything on Linux i386 and Win32, but it should be possible to make it work on 64 bit systems with little effort.

**Comment by Iowaguy2** [comment]
I was able to build and get text on the screen by copying a font file into the directory of the executable. I copied Files/Oberon10b.Scn.Fnt to the executable directory, renamed it to "Oberon10.Scn.Fnt" as indicated in ObFonts.cpp::_init().  This was on a debian 64bit system.  FWIW.  (not sure of next steps...)

**Comment by rochus-keller** [comment]
Please use the current version of the Oberon+ IDE and the SDL version of the OberonSystem (https://github.com/rochus-keller/OberonSystem/blob/FFI/OberonSystemSdl.obxpro). There is a precompiled version for Windows, Linux and Mac which includes everything, also the mentioned SDL OberonSystem in the examples folder.
